services:
  - type: web
    name: cityart-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: NODE_ENV
        value: production
